#ifndef PICTURE_PREPROCESSOR_RESOURCE_H
#define PICTURE_PREPROCESSOR_RESOURCE_H

#define IDC_STATIC -1

#define IDI_MYEXEICON 201
#define IDI_MYICON 202

#define IDD_CONFIGURE 300
#define IDC_WIDTH 301
#define IDC_HEIGHT 302
#define IFC_INTERFACENAME 304
#endif
